---
sudo: required
language: python
services: docker


env:
  global:
    - ROLE_NAME: memcached
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd


install:
  - pip install ansible
  - pip install ansible-lint
  - pip install docker
  - pip install molecule
  - pip install netaddr
  - pip install testinfra

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME cyber01.$ROLE_NAME
  - cd cyber01.$ROLE_NAME


# Let`s go tests
script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
